[book]
authors = ["Linus-Mussmaecher"]
language = "en"
multilingual = false
src = "src"
title = "Cellumina - Cellular Automata in Rust"

[rust]
edition = "2021"


[output.html]
additional-css = ["imagecaptions.css"]