row_boundary = "Periodic"
col_boundary = "Periodic"

[[patterns]]
chance = 1.0
priority = 1.0

[patterns.before]
data = [1, 0]
cols = 1

[patterns.after]
data = [0, 1]
cols = 1

[[patterns]]
chance = 0.800000011920929
priority = 0.5

[patterns.before]
data = [1, 0, 1, 0]
cols = 2

[patterns.after]
data = [0, 0, 1, 1]
cols = 2

[[patterns]]
chance = 0.800000011920929
priority = 0.5

[patterns.before]
data = [0, 1, 0, 1]
cols = 2

[patterns.after]
data = [0, 0, 1, 1]
cols = 2
